"""add marital_status, age, disability to profile

Revision ID: 1406c6f8a11c
Revises: a81542d339a8
Create Date: 2025-08-23 19:15:53.653334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1406c6f8a11c'
down_revision = 'a81542d339a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marital_status', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('disability', sa.String(length=120), nullable=True))
        batch_op.drop_column('salary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('disability')
        batch_op.drop_column('age')
        batch_op.drop_column('marital_status')

    # ### end Alembic commands ###
