"""initial postgres schema

Revision ID: 245d18319c53
Revises: 1406c6f8a11c
Create Date: 2026-06-24 19:59:50.641511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245d18319c53'
down_revision = '1406c6f8a11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_deletions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_deletions_message_id'))
        batch_op.drop_index(batch_op.f('ix_message_deletions_user_id'))

    op.drop_table('message_deletions')
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reaction_message_id'))
        batch_op.drop_index(batch_op.f('ix_reaction_user_id'))

    op.drop_table('reaction')
    op.drop_table('push_prompt_state')
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_block_pair'), type_='unique')

    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('expires_at')
        batch_op.drop_column('max_uses')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_message_convo'))

    with op.batch_alter_table('message_hidden', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_message_hidden_message_id'))
        batch_op.drop_index(batch_op.f('idx_message_hidden_user_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hidden_at')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('specialties_other',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('hourly_rate',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('services_other',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('care_needed_other',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('country_code')
        batch_op.drop_column('preferred_services_other')
        batch_op.drop_column('any_medical_condition')
        batch_op.drop_column('availability_end')
        batch_op.drop_column('family_disability_details')
        batch_op.drop_column('caregiver_services_needed')
        batch_op.drop_column('availability_start')
        batch_op.drop_column('family_disability')
        batch_op.drop_column('preferred_services')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('reported_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_report_target_id'))
        batch_op.create_index(batch_op.f('ix_report_reported_id'), ['reported_id'], unique=False)
        batch_op.drop_column('kind')
        batch_op.drop_column('target_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('push_notifications_enabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('push_notifications_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('kind', sa.VARCHAR(length=40), nullable=False))
        batch_op.drop_index(batch_op.f('ix_report_reported_id'))
        batch_op.create_index(batch_op.f('ix_report_target_id'), ['target_id'], unique=False)
        batch_op.alter_column('reported_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_services', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('family_disability', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('availability_start', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('caregiver_services_needed', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('family_disability_details', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('availability_end', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('any_medical_condition', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('preferred_services_other', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('country_code', sa.VARCHAR(length=2), nullable=True))
        batch_op.alter_column('published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('care_needed_other',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('services_other',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('hourly_rate',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('specialties_other',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('message_hidden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden_at', sa.DATETIME(), nullable=False))
        batch_op.create_foreign_key(None, 'message', ['message_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_message_hidden_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_message_hidden_message_id'), ['message_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_message_convo'), ['conversation_id'], unique=False)

    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_uses', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_block_pair'), ['blocker_id', 'blocked_id'])

    op.create_table('push_prompt_state',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('decision', sa.VARCHAR(length=20), nullable=True),
    sa.Column('shown_at', sa.DATETIME(), nullable=True),
    sa.Column('decided_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('reaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('emoji', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name=op.f('_message_user_emoji_uc'))
    )
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reaction_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reaction_message_id'), ['message_id'], unique=False)

    op.create_table('message_deletions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name=op.f('uq_msg_user_delete'))
    )
    with op.batch_alter_table('message_deletions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_deletions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_deletions_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###
